version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
    depends_on: 
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/bookstore
      REDIS_URL: redis://redis:6379
    ports:
      - "4000:4000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: bookstore
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
       - postgres-db:/data/postgres
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
volumes:
  postgres-db:
    driver: local